name = "Gabe Furber"
license = "MIT"
licenselink = "https://github.com/furbski/gabefurber/blob/master/LICENSE"
description = ""
homepage = "https://gabefurber.com/"
tags = ["blog"]
features = ["dark mode", "grid view"]
min_version = "0.55.0"

[author]
    name = "The New Dynamic"
    homepage = "https://www.thenewdynamic.com/"

# If porting an existing theme
[original]
    author = "Narative"
    homepage = "https://www.narative.co/"
    repo = "https://github.com/narative/gatsby-theme-novela"
